---
- hosts: all
  become: true
  vars:
   companyname: MithunTechnologies
   location: bangalore
  tasks:
  - name: install Appcche HTTP Server
    yum: 
     name: httpd
     state: latest
  - name: copy index.html file   
    copy:                        
     src: index.html             
     dest: /var/www/html/index.html   
  - name: start Appache HTTP Server
    service:
     name: httpd
     state: started
     enabled: true
...

