---
- hosts: all
  become: true
  tasks:
  - name: install Git
    yum:
      name: git
      state: absent
  - name: install HTTPD server
    yum:
      name: httpd
      state: absent
  - name: install tree
    yum:
      name: tree
      state: absent
  - name: install unzip
    yum:
      name: unzip
      state: absent
...



