---
- hosts: all
  become: true
  tasks:
   - name: install list of packages
     yum: name="{{item}}" state=present
     with_items:
      - git
      - httpd
      - zip
      - unzip
      - nano
      - wget
...


